# Generated by Django 4.1.2 on 2022-10-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='bio',
            new_name='adress',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
