# Generated by Django 4.1.2 on 2022-10-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_bio_usermodel_adress_usermodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='adress',
            new_name='address',
        ),
    ]
